Repository City-of-Helsinki/servicemap, pull requests merged in 2019-01, with the labels that each got.

#592 Fix/personalisation ui fixes
  src/views/route-settings.coffee
  styles/personalisation.less
  views/templates/mixins/personalisation-mode.jade
Labels: in progress

#597 Fix/show only transits on high zoom
  src/app-state.coffee
  src/app.coffee
  src/control.coffee
  src/map-base-view.coffee
  src/map-view.coffee
Labels: in progress

#595 Fix/screen reader navigation fixes
  src/views/personalisation.coffee
  styles/personalisation.less
  views/templates/language-selector.jade
  views/templates/personalisation.jade
Labels: accessibility, in progress, jade

#598 Fix/search result accessibility
  locales/app.yaml
  src/views/details.coffee
  src/views/new-search-results.coffee
  src/views/service-cart.coffee
  src/views/unit-details.coffee
  views/templates/details.jade
  views/templates/event-list-row.jade
  views/templates/event.jade
  views/templates/feature-tour-start.jade
  views/templates/language-selector.jade
  views/templates/loading-indicator.jade
  views/templates/location-refresh-button.jade
  views/templates/measure-close-button.jade
  views/templates/mixins/personalisation-mode.jade
  views/templates/navigation-browse.jade
  views/templates/navigation-header.jade
  views/templates/navigation-search.jade
  views/templates/new-search-results.jade
  views/templates/personalisation.jade
  views/templates/search-results.jade
  views/templates/service-cart.jade
  views/templates/service-tree.jade
  views/templates/sidebar-loading-indicator.jade
  views/templates/tool-menu.jade
Labels: in progress

#599 Fix/tool menu navigation and accessibility
  locales/app.yaml
  src/views/base.coffee
  src/views/tool-menu.coffee
  views/templates/disclaimers-overlay.jade
  views/templates/tool-menu.jade
Labels: accessibility, in progress

#601 Add descriptive text to elements for screen readers
  locales/app.yaml
  src/views/search-input.coffee
  views/templates/details.jade
  views/templates/location-refresh-button.jade
  views/templates/navigation-header.jade
  views/templates/new-search-results.jade
  views/templates/personalisation.jade
Labels: accessibility, in progress

#602 Fix/hide map options from screen readers
  src/map-view.coffee
  src/views/service-cart.coffee
Labels: accessibility, in progress

#606 Remove bug caused by old styling
  styles/map-controls.less
Labels: in progress

#605 Removed expand event to prevent details page closing when clicking the search-field
  src/views/search-input.coffee
Labels: in progress

#600 Fix/feedback service type selection on keyboard
  locales/app.yaml
  src/views/feedback-form.coffee
  styles/feedback-form.less
  views/templates/unit-feedback-form.jade
Labels: in progress

#604 Fix/accessibility navigation improvement
  locales/app.yaml
  src/views/new-search-results.coffee
  src/views/position-details.coffee
  views/templates/disclaimers-overlay.jade
  views/templates/navigation-layout.jade
  views/templates/new-search-results.jade
  views/templates/position.jade
  views/templates/tool-menu.jade
Labels: accessibility, in progress
